HepsiOrada/HepsiOrada_UI/Models/HeaderViewModel.cs
using Entity.POCO;

namespace HepsiOrada_UI.Models
{
    public class HeaderViewModel
    {
        public List<Category> Category { get; set; }
    }
}

HepsiOrada/HepsiOrada_UI/Component/HeaderViewComponent.cs
using BusinessLogicLayer.Abstract;
using HepsiOrada_UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace HepsiOrada_UI.Component
{
    //View Component , Partial View yapısının alternatifidir. Örnek için, ufak bir veritabanı işleminde Controller yapısını kullanmadan veri alıp işlememizi sağlayan yapıdır. Aşağıdaki örnekte Header Class'ın adıyken ViewComponent'ı otomatik olarak görmektedir. Sayfalarımızın Header yapısını bu Component içinde tuttuk. Header'a veri çekmek istediğimizde , Layout'un içinde veri çekemeyiz ama component içinde çekebiliriz, bize böyle bir faydası oldu burada.
    public class HeaderViewComponent:ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HeaderViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            HeaderViewModel model = new HeaderViewModel();
            var categories = categoryService.GetCategory();
            switch (categories.ResultType)
            {
                case Core.Constant.EntityResultType.Success:
                    model.Category = categories.Data.ToList();
                    break;
                case Core.Constant.EntityResultType.Error:
                    break;
                case Core.Constant.EntityResultType.NonVAlidation:
                    break;
                case Core.Constant.EntityResultType.NotFound:
                    break;
                case Core.Constant.EntityResultType.Warning:
                    break;
            }
            return View(model);
        }
    }
}

HepsiOrada/HepsiOrada_UI/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace HepsiOrada_UI.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HepsiOrada/HepsiOrada_UI/Controllers/BasketController.cs
    using BusinessLogicLayer.Abstract;
using Entity.DTO;
using Entity.POCO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BusinessLogicLayer.Abstract;

namespace HepsiOrada_UI.Controllers
{
    //Sadece kullanıcıların sepet işlemi yapabilmesini, adminlerin (mesela) sepet işlemi yapamamasını sağlayan attribute.
    [Authorize(Roles = "UserApp")]
    public class BasketController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly IProductService productService;
        private readonly IBasketService basketService;

        public BasketController(IBasketService basketService,UserManager<AppUser> userManager,IProductService productService)
        {
            this.userManager = userManager;
            this.productService = productService;
            this.basketService = basketService;
        }
        [HttpPost]
        public async Task<IActionResult> AddToBasket(int count, int productId)
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.AddToBasket(new Entity.DTO.BasketDTO
            {
                Count = count,
                ProductId = productId,
                UserID = user.Id
            });
            switch (result.EntityResultType)
            {
                case Core.Constant.EntityResultType.Success:

                    //Asp.Net Core Mvc kütüphanesinde bulunan ve 200 (Http durum kodu) işlemin başarılı olduğunu ifade eden kodu verdiren method.
                    return Ok();
                case Core.Constant.EntityResultType.Error:
                    break;
                case Core.Constant.EntityResultType.NotFound:
                    break;
                case Core.Constant.EntityResultType.NonVAlidation:
                    break;
                case Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            //Asp.Net Core Mvc kütüphanesinde bulunan ve 404 (Http durum kodu) no'lu hata kodunu verdiren method.
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> RefreshBasketCount()
        {
            var u = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.Get(u.Id);
            switch (result.EntityResultType)        
            {
                case Core.Constant.EntityResultType.Success:
                    return Ok(result.Data.Sum(x=>x.Count));
                case Core.Constant.EntityResultType.Error:
                    break;
                case Core.Constant.EntityResultType.NotFound:
                    break;
                case Core.Constant.EntityResultType.NonVAlidation:
                    break;
                case Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View();
        }
        public async Task<IActionResult> Sepet()
        {
            var u = await userManager.FindByNameAsync(User.Identity.Name);
            var result = productService.GetBasketByProductID(u.Id);
            switch (result.EntityResultType)
            {
                case Core.Constant.EntityResultType.Success:
                    return View(result.Data);   
                case Core.Constant.EntityResultType.Error:
                    break;
                case Core.Constant.EntityResultType.NotFound:
                    break;
                case Core.Constant.EntityResultType.NonVAlidation:
                    break;
                case Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return NotFound();
        }
        public async Task<IActionResult> CountChange(int id,int count)
        {
            var u = await userManager.FindByNameAsync(User.Identity.Name);
            var result = basketService.Update(count, id, u.Id);
            switch (result.EntityResultType)
            {
                case Core.Constant.EntityResultType.Success:
                    return Ok();
                case Core.Constant.EntityResultType.Error:
                    break;
                case Core.Constant.EntityResultType.NotFound:
                    break;
                case Core.Constant.EntityResultType.NonVAlidation:
                    break;
                case Core.Constant.EntityResultType.Warning:
                    break;
                default:
                    break;
            }
            return View();
        }
    }
}

HepsiOrada/HepsiOrada_UI/Controllers/LaptopController.cs
using BusinessLogicLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace HepsiOrada_UI.Controllers
{
    public class LaptopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HepsiOrada/HepsiOrada_UI/Controllers/TelefonController.cs
using Microsoft.AspNetCore.Mvc;

namespace HepsiOrada_UI.Controllers
{
    public class TelefonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HepsiOrada/HepsiOrada_UI/Views/Shared/Components/Header/Default.cshtml
@model HeaderViewModel
     <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@hepsiorada.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">0 850 444 44 44</a>
                </div>
                <div>
                    <a class="text-light" href="https://www.instagram.com/okan.kandemirr/?hl=tr" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://twitter.com/okann38" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/in/okan-kandemir-77427014b/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->


    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a asp-controller="Home" asp-action="Index" class="navbar-brand text-success logo h1 align-self-center">
                HepsiOrada
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="AboutUs" asp-action="Index" class="nav-link">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Laptop" asp-action="Index" class="nav-link">Laptop</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Bilgisayar" asp-action="Index" class="nav-link">Bilgisayar</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Telefon" asp-action="Index" class="nav-link">Akıllı Telefon</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div>
                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                        <i class="fa fa-fw fa-search text-dark mr-2"></i>
                    </a>
                    <a class="nav-icon position-relative text-decoration-none" asp-controller="Basket" asp-action="Sepet">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1" id=></i>
                    <span id="bsk"></span>
                        @*Sepete Eklenilen ürün sayısını js ile gireceğimiz kısım.*@
                        @*<span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark"></span>*@
                    </a>
                        <div class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Account" asp-action="LogOut" class="nav-link"><i class="fa fa-user"></i> @User.Identity.Name</a>
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login" class="nav-link"><i class="fa fa-user"></i> Giriş</a>
                }
                        </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Header -->